apiVersion: v1
kind: Secret
metadata:
  name: voting-app-secrets
  namespace: voting-app
type: Opaque
data:
  # postgres / postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=